services:
  db:
    image: postgres:15-alpine
    container_name: wata_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: wata_internship
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: wata_ap
    restart: unless-stopped
    depends_on:
      - db
    ports:
      - '3000:3000'
    environment:
      PORT: 3000
      DATABASE_URL: postgresql://admin:password123@db:5432/wata_internship?schema=public
      JWT_SECRET: supersecretjwtkey
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules

volumes:
  pgdata:
